# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 15:30
from __future__ import unicode_literals

import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('sidebar_order', models.CharField(choices=[('last', 'Last'), ('first', 'First')], default='last', max_length=50)),
                ('non_emergency_callout', models.BooleanField(default=True, help_text='Shows/hides the call 111 section', verbose_name='Non-emergency callout')),
                ('choices_origin', models.CharField(blank=True, help_text='Optional. Related Choices page (e.g. conditions/stomach-ache-abdominal-pain/Pages/Introduction.aspx)', max_length=255)),
                ('local_header', wagtail.wagtailcore.fields.StreamField((('markdown', wagtail.wagtailcore.blocks.RichTextBlock(label='markdown')),), blank=True, null=True)),
                ('main', wagtail.wagtailcore.fields.StreamField((('markdown', wagtail.wagtailcore.blocks.RichTextBlock(label='markdown')), ('calloutInfo', wagtail.wagtailcore.blocks.RichTextBlock(label='callout info'))), blank=True, null=True)),
                ('sidebar', wagtail.wagtailcore.fields.StreamField((('markdown', wagtail.wagtailcore.blocks.RichTextBlock(label='markdown')), ('calloutAlert', wagtail.wagtailcore.blocks.RichTextBlock(label='callout alert'))), blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
