# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 08:17
from __future__ import unicode_literals

import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks
from django.db import migrations

import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplepage',
            name='before',
            field=wagtail.wagtailcore.fields.StreamField((('markdown', wagtailmarkdown.fields.MarkdownBlock(label='markdown')), ('figureList', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailimages.blocks.ImageChooserBlock(), label='figure list'))), blank=True, null=True),
        ),
    ]
