# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 10:27
from __future__ import unicode_literals

from django.db import migrations
import images.blocks
import pages.blocks
import wagtail.wagtailcore.fields
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplepage',
            name='before',
            field=wagtail.wagtailcore.fields.StreamField((('markdown', wagtailmarkdown.fields.MarkdownBlock(label='markdown')), ('figureList', pages.blocks.ListBlock(images.blocks.ImageChooserBlock(), label='figure list'))), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simplepage',
            name='main',
            field=wagtail.wagtailcore.fields.StreamField((('markdown', wagtailmarkdown.fields.MarkdownBlock(label='markdown')), ('calloutInfo', wagtailmarkdown.fields.MarkdownBlock(label='callout info')), ('calloutWarning', wagtailmarkdown.fields.MarkdownBlock(label='callout warning'))), blank=True, null=True),
        ),
    ]
