# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20161014_1027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimplePage',
            new_name='EditorialPage',
        ),
    ]
