# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 15:30
from __future__ import unicode_literals

import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
from django.db import migrations

import images.blocks
import pages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('pages', '0004_folderpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='editorialpage',
            name='local_header',
            field=wagtail.wagtailcore.fields.StreamField((('markdown', wagtail.wagtailcore.blocks.RichTextBlock(label='markdown')), ('sectionNav', pages.blocks.StaticBlock('Section Navigation', label='section nav'))), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='editorialpage',
            name='main',
            field=wagtail.wagtailcore.fields.StreamField((('markdown', wagtail.wagtailcore.blocks.RichTextBlock(label='markdown')), ('calloutInfo', wagtail.wagtailcore.blocks.RichTextBlock(label='callout info')), ('calloutWarning', wagtail.wagtailcore.blocks.RichTextBlock(label='callout warning')), ('sectionList', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('sections', pages.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('content', wagtail.wagtailcore.blocks.StreamBlock((('image', images.blocks.ImageChooserBlock(label='image')), ('markdown', wagtail.wagtailcore.blocks.RichTextBlock(label='markdown')))))))))), label='section list'))), blank=True, null=True),
        ),
    ]
