# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 14:07
from __future__ import unicode_literals

import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
from django.db import migrations

import images.blocks
import pages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20161118_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialpage',
            name='main',
            field=wagtail.wagtailcore.fields.StreamField((('markdown', wagtail.wagtailcore.blocks.RichTextBlock(label='markdown')), ('sectionList', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('sections', pages.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('content', wagtail.wagtailcore.blocks.StreamBlock((('image', images.blocks.ImageChooserBlock(label='image')), ('markdown', wagtail.wagtailcore.blocks.RichTextBlock(label='markdown')))))))))), label='section list'))), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='editorialpage',
            name='sidebar',
            field=wagtail.wagtailcore.fields.StreamField((('markdown', wagtail.wagtailcore.blocks.RichTextBlock(label='markdown')),), blank=True, null=True),
        ),
    ]
