# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 17:14
from __future__ import unicode_literals

import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20161121_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorialpage',
            name='before',
        ),
        migrations.RemoveField(
            model_name='editorialpage',
            name='local_header',
        ),
        migrations.RemoveField(
            model_name='editorialpage',
            name='sidebar',
        ),
        migrations.RemoveField(
            model_name='editorialpage',
            name='sidebar_order',
        ),
        migrations.AddField(
            model_name='editorialpage',
            name='header',
            field=wagtail.wagtailcore.fields.StreamField((('markdown', wagtail.wagtailcore.blocks.RichTextBlock(label='markdown')),), blank=True, null=True, verbose_name='Header Content'),
        ),
        migrations.AlterField(
            model_name='editorialpage',
            name='main',
            field=wagtail.wagtailcore.fields.StreamField((('markdown', wagtail.wagtailcore.blocks.RichTextBlock(label='markdown')),), blank=True, null=True, verbose_name='Main Content'),
        ),
    ]
