# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 13:39
from __future__ import unicode_literals

from django.db import migrations


def increase_path(path):
    return '%s%s' % (path[:-1], (int(path[-1]) + 1))


def forwards_func(apps, schema_editor):
    # Get models
    ContentType = apps.get_model('contenttypes.ContentType')
    Page = apps.get_model('wagtailcore.Page')
    FolderPage = apps.get_model('pages.FolderPage')
    HomePage = apps.get_model('home.HomePage')

    # Create content type for the folderpage model
    folderpage_content_type, created = ContentType.objects.get_or_create(
        model='folderpage', app_label='pages')

    home = HomePage.objects.first()
    latest_path = '00010001000%s' % home.numchild
    added = 0

    # create symptoms page if necessary
    if not Page.objects.filter(slug='symptoms').count():
        latest_path = increase_path(latest_path)
        FolderPage.objects.create(
            title="Symptoms",
            slug='symptoms',
            content_type=folderpage_content_type,
            path=latest_path,
            depth=3,
            numchild=0,
            url_path='/home/symptoms/',
            guide=False
        )
        added += 1

    # create conditions page if necessary
    if not Page.objects.filter(slug='conditions').count():
        latest_path = increase_path(latest_path)
        FolderPage.objects.create(
            title="Conditions",
            slug='conditions',
            content_type=folderpage_content_type,
            path=latest_path,
            depth=3,
            numchild=0,
            url_path='/home/conditions/',
            guide=False
        )
        added += 1

    # update home.numchild if necessary
    if added:
        home.numchild += added
        home.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20170207_1203'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
