# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailimages.Image')),
                ('caption', models.CharField(blank=True, help_text='Optional. It will be displayed below the image.', max_length=255)),
                ('alt', models.CharField(blank=True, help_text='Optional. Alternate text for an image, if the image cannot be displayed.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailimages.image',),
        ),
    ]
