# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='image.jpg', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
