# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20161014_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='alt',
        ),
    ]
